/**
 * 포털 목업 데이터 (데모·정적 UI용). 추후 API 응답으로 교체.
 */
(function (global) {
  "use strict";

  var PROPERTIES = [
    {
      id: "home-1",
      name: "첫 번째 유후공간",
      address: "경북 포항시 북구 ○○로 12",
      hostId: "host-a",
      status: "active",
      summary: "우드·화이트 톤 유후시설 재생 숙소",
      region: "경북",
      locationLabel: "경북 포항",
      pricePerNight: 95000,
      rating: 4.92,
      reviewCount: 31,
      guests: 4,
      bedrooms: 2,
      beds: 3,
      baths: 1,
      propertyType: "전체 숙소",
      amenities: ["주방", "와이파이", "무료 주차", "세탁기", "야외 정원"],
      photos: [
        "../Asset/Home_1/after/Home_1_after_08.jpeg",
        "../Asset/Home_1/after/Home_1_after_09.jpeg",
        "../Asset/Home_1/after/Home_1_after_12.jpeg",
      ],
      hostName: "민수",
      hostBio: "마을 재생 숙소를 함께 운영합니다.",
      description:
        "오래 비어 있던 유후시설을 정리한 체류형 숙소입니다. 2~4인 가족·친구 여행에 적합합니다.",
    },
    {
      id: "home-2",
      name: "마을 끝 작은채",
      address: "전남 순천시 ○○면 ○○리 8",
      hostId: "host-b",
      status: "active",
      summary: "단독 체류형, 조용한 마을 풍경",
      region: "전남",
      locationLabel: "전남 순천",
      pricePerNight: 72000,
      rating: 4.78,
      reviewCount: 19,
      guests: 2,
      bedrooms: 1,
      beds: 1,
      baths: 1,
      propertyType: "독채",
      amenities: ["와이파이", "주차", "테라스", "바베큐"],
      photos: [],
      photoTheme: "forest",
      hostName: "지연",
      hostBio: "마을 풍경을 살린 소규모 숙소를 운영합니다.",
      description: "마을 끝 언덕의 작은채. 창밖으로 논과 산책로가 보입니다.",
    },
    {
      id: "home-3",
      name: "옛 학당 옆 게스트룸",
      address: "전남 담양군 ○○면 ○○리 3",
      hostId: "host-a",
      status: "paused",
      summary: "리노베이션 준비 중",
      region: "전남",
      locationLabel: "전남 담양",
      pricePerNight: 68000,
      rating: 4.65,
      reviewCount: 8,
      guests: 3,
      bedrooms: 1,
      beds: 2,
      baths: 1,
      propertyType: "게스트룸",
      amenities: ["와이파이", "공용 주방"],
      photos: [],
      photoTheme: "hanok",
      hostName: "민수",
      hostBio: "학당 인근 공간 리노베이션 준비 중입니다.",
      description: "옛 학당 옆 부속 공간. 현재 예약은 일시 중단되었습니다.",
    },
    {
      id: "home-4",
      name: "한옥 마당 스테이",
      address: "전북 전주시 완산구 ○○길 24",
      hostId: "host-c",
      status: "active",
      summary: "한옥 마당과 돌담길이 있는 전주 한옥 숙소",
      region: "전북",
      locationLabel: "전북 전주",
      pricePerNight: 118000,
      rating: 4.89,
      reviewCount: 54,
      guests: 5,
      bedrooms: 2,
      beds: 3,
      baths: 1,
      propertyType: "한옥",
      amenities: ["한옥 체험", "와이파이", "주차", "전통 다실", "정원"],
      photos: [],
      photoTheme: "hanok",
      hostName: "서연",
      hostBio: "전주 한옥마을 인근, 전통과 편안함을 함께 제공합니다.",
      description: "한옥 마당에서 차를 마시며 쉬는 숙소. 한복 체험·골목 산책 추천.",
    },
    {
      id: "home-5",
      name: "제주 돌담 옆 작은집",
      address: "제주 서귀포시 ○○리 45",
      hostId: "host-d",
      status: "active",
      summary: "돌담·감귤밭이 보이는 서귀포 독채",
      region: "제주",
      locationLabel: "제주 서귀포",
      pricePerNight: 142000,
      rating: 4.95,
      reviewCount: 87,
      guests: 4,
      bedrooms: 2,
      beds: 2,
      baths: 2,
      propertyType: "독채",
      amenities: ["바다 전망", "와이파이", "주차", "취사 가능", "테라스"],
      photos: [],
      photoTheme: "ocean",
      hostName: "하준",
      hostBio: "제주에서 8년째 로컬 숙소를 운영하고 있습니다.",
      description: "서귀포 바다와 오름이 가까운 독채. 렌트카 여행에 적합합니다.",
    },
    {
      id: "home-6",
      name: "강릉 바다 보이는 loft",
      address: "강원 강릉시 ○○해변로 102",
      hostId: "host-e",
      status: "active",
      summary: "해변 도보 5분, 오션뷰 로프트",
      region: "강원",
      locationLabel: "강원 강릉",
      pricePerNight: 128000,
      rating: 4.88,
      reviewCount: 62,
      guests: 3,
      bedrooms: 1,
      beds: 2,
      baths: 1,
      propertyType: "로프트",
      amenities: ["오션뷰", "와이파이", "엘리베이터", "주차", "커피머신"],
      photos: [],
      photoTheme: "ocean",
      hostName: "수빈",
      hostBio: "강릉 로컬 가이드이자 숙소 호스트입니다.",
      description: "일출·해변 산책 후 돌아와 쉬기 좋은 오픈형 로프트입니다.",
    },
    {
      id: "home-7",
      name: "평창 숲속 A-frame",
      address: "강원 평창군 ○○면 ○○리 7",
      hostId: "host-f",
      status: "active",
      summary: "삼나무 숲 속 A-frame 통나무집",
      region: "강원",
      locationLabel: "강원 평창",
      pricePerNight: 165000,
      rating: 4.97,
      reviewCount: 41,
      guests: 4,
      bedrooms: 2,
      beds: 2,
      baths: 1,
      propertyType: "통나무집",
      amenities: ["벽난로", "와이파이", "주차", "숲 산책로", "바베큐"],
      photos: [],
      photoTheme: "mountain",
      hostName: "도윤",
      hostBio: "겨울 스포츠·힐링 스테이를 기획합니다.",
      description: "눈 내리는 겨울, 녹음 가득한 여름 모두 인기 있는 숲속 숙소입니다.",
    },
    {
      id: "home-8",
      name: "경주 황리단길 게스트하우스",
      address: "경북 경주시 황남동 ○○로 3",
      hostId: "host-c",
      status: "active",
      summary: "황리단길 도보 3분, 도미토리·개인실",
      region: "경북",
      locationLabel: "경북 경주",
      pricePerNight: 38000,
      rating: 4.71,
      reviewCount: 112,
      guests: 1,
      bedrooms: 1,
      beds: 1,
      baths: 1,
      propertyType: "게스트하우스",
      amenities: ["공용 주방", "와이파이", "세탁", "라운지", "자전거 대여"],
      photos: [],
      photoTheme: "hanok",
      hostName: "서연",
      hostBio: "배낭 여행객을 위한 편안한 공간을 만듭니다.",
      description: "혼행·친구 여행에 부담 없는 가격. 야경·유적지 산책에 최적입니다.",
    },
    {
      id: "home-9",
      name: "부산 광안리 스튜디오",
      address: "부산 수영구 광안해변로 ○○",
      hostId: "host-g",
      status: "active",
      summary: "광안대교 야경이 보이는 스튜디오",
      region: "부산",
      locationLabel: "부산 광안리",
      pricePerNight: 89000,
      rating: 4.83,
      reviewCount: 73,
      guests: 2,
      bedrooms: 1,
      beds: 1,
      baths: 1,
      propertyType: "아파트",
      amenities: ["야경", "와이파이", "엘리베이터", "주차", "근처 맛집"],
      photos: [],
      photoTheme: "sunset",
      hostName: "예린",
      hostBio: "부산 로컬 맛집·산책 코스를 안내해 드립니다.",
      description: "광안리 해변과 대교 야경을 즐기는 커플·친구 여행에 인기입니다.",
    },
    {
      id: "home-10",
      name: "여수 밤바다 펜션",
      address: "전남 여수시 ○○해안로 88",
      hostId: "host-b",
      status: "active",
      summary: "여수 밤바다 뷰, 가족형 펜션",
      region: "전남",
      locationLabel: "전남 여수",
      pricePerNight: 110000,
      rating: 4.76,
      reviewCount: 36,
      guests: 6,
      bedrooms: 3,
      beds: 4,
      baths: 2,
      propertyType: "펜션",
      amenities: ["바다 전망", "주방", "와이파이", "주차", "바베큐"],
      photos: [],
      photoTheme: "ocean",
      hostName: "지연",
      hostBio: "남해안 풍경을 살린 가족 숙소를 운영합니다.",
      description: "넓은 거실과 테라스에서 여수 밤바다를 감상할 수 있습니다.",
    },
    {
      id: "home-11",
      name: "춘천 남이섬 근처 캐빈",
      address: "강원 춘천시 ○○로 55",
      hostId: "host-f",
      status: "active",
      summary: "호수 근처 조용한 캐빈",
      region: "강원",
      locationLabel: "강원 춘천",
      pricePerNight: 78000,
      rating: 4.74,
      reviewCount: 28,
      guests: 3,
      bedrooms: 1,
      beds: 2,
      baths: 1,
      propertyType: "캐빈",
      amenities: ["호수 근처", "와이파이", "주차", "캠프파이어", "자전거"],
      photos: [],
      photoTheme: "forest",
      hostName: "도윤",
      hostBio: "춘천·남이섬 당일치기와 연계하기 좋습니다.",
      description: "닭갈비·막국수 맛집과 남이섬 보트 투어를 추천합니다.",
    },
    {
      id: "home-12",
      name: "안동 하회마을 한옥",
      address: "경북 안동시 풍천면 ○○리 2",
      hostId: "host-h",
      status: "active",
      summary: "하회마을 인근 전통 한옥 체류",
      region: "경북",
      locationLabel: "경북 안동",
      pricePerNight: 135000,
      rating: 4.91,
      reviewCount: 47,
      guests: 4,
      bedrooms: 2,
      beds: 2,
      baths: 1,
      propertyType: "한옥",
      amenities: ["한옥", "와이파이", "주차", "전통 체험", "정원"],
      photos: [],
      photoTheme: "hanok",
      hostName: "정호",
      hostBio: "하회탈·전통 문화 프로그램을 연결합니다.",
      description: "하회마을 산책과 안동찜·간고등어 맛집을 함께 즐겨 보세요.",
    },
    {
      id: "home-13",
      name: "속초 해변 근처 아파트",
      address: "강원 속초시 ○○해변로 201",
      hostId: "host-e",
      status: "active",
      summary: "속초 해변·중앙시장 도보권",
      region: "강원",
      locationLabel: "강원 속초",
      pricePerNight: 98000,
      rating: 4.8,
      reviewCount: 55,
      guests: 5,
      bedrooms: 2,
      beds: 3,
      baths: 1,
      propertyType: "아파트",
      amenities: ["해변 근처", "와이파이", "엘리베이터", "주차", "주방"],
      photos: [],
      photoTheme: "ocean",
      hostName: "수빈",
      hostBio: "속초 당근시장·아바이마을 코스를 안내합니다.",
      description: "가족 단위로 속초 해변과 시장을 누비기 좋은 아파트입니다.",
    },
    {
      id: "home-14",
      name: "남해 섬마을 독채",
      address: "경남 남해군 ○○면 ○○리 19",
      hostId: "host-i",
      status: "active",
      summary: "남해 바다와 섬 풍경이 보이는 독채",
      region: "경남",
      locationLabel: "경남 남해",
      pricePerNight: 102000,
      rating: 4.86,
      reviewCount: 33,
      guests: 4,
      bedrooms: 2,
      beds: 2,
      baths: 1,
      propertyType: "독채",
      amenities: ["바다 전망", "와이파이", "주차", "테라스", "조용한 마을"],
      photos: [],
      photoTheme: "rural",
      hostName: "유진",
      hostBio: "남해 드라이브·카페 투어를 좋아합니다.",
      description: "조용한 섬마을에서 며칠 머물며 바다와 숲을 오가기 좋습니다.",
    },
    {
      id: "home-15",
      name: "가평 북한강 글램핑",
      address: "경기 가평군 ○○면 ○○리 30",
      hostId: "host-j",
      status: "active",
      summary: "북한강 뷰 글램핑 텐트",
      region: "경기",
      locationLabel: "경기 가평",
      pricePerNight: 85000,
      rating: 4.72,
      reviewCount: 64,
      guests: 4,
      bedrooms: 1,
      beds: 2,
      baths: 1,
      propertyType: "글램핑",
      amenities: ["강 전망", "바베큐", "와이파이", "주차", "캠프파이어"],
      photos: [],
      photoTheme: "forest",
      hostName: "태희",
      hostBio: "서울 근교 1박 2일 힐링을 기획합니다.",
      description: "주말 캠핑 감성을 편의시설과 함께 즐길 수 있는 글램핑입니다.",
    },
    {
      id: "home-16",
      name: "보령 머드 축제 근처 스테이",
      address: "충남 보령시 ○○해안로 15",
      hostId: "host-k",
      status: "active",
      summary: "대천·보령 해안가 스테이",
      region: "충남",
      locationLabel: "충남 보령",
      pricePerNight: 69000,
      rating: 4.69,
      reviewCount: 22,
      guests: 4,
      bedrooms: 2,
      beds: 2,
      baths: 1,
      propertyType: "펜션",
      amenities: ["해변 근처", "와이파이", "주차", "주방", "세탁기"],
      photos: [],
      photoTheme: "ocean",
      hostName: "현우",
      hostBio: "서해안 해수욕·축제 시즌 숙소를 운영합니다.",
      description: "여름 해수욕·가을 드라이브에 적합한 해안가 펜션입니다.",
    },
    {
      id: "home-17",
      name: "통영 동피랑 언덕집",
      address: "경남 통영시 ○○로 9",
      hostId: "host-i",
      status: "active",
      summary: "동피랑 벽화마을 언덕 위 작은집",
      region: "경남",
      locationLabel: "경남 통영",
      pricePerNight: 92000,
      rating: 4.84,
      reviewCount: 39,
      guests: 3,
      bedrooms: 1,
      beds: 2,
      baths: 1,
      propertyType: "단독주택",
      amenities: ["마을 전망", "와이파이", "주차", "테라스", "근처 카페"],
      photos: [],
      photoTheme: "sunset",
      hostName: "유진",
      hostBio: "통영·거제 섬 여행 베이스로 추천합니다.",
      description: "동피랑 골목과 항구 야경을 걸으며 쉬기 좋은 언덕집입니다.",
    },
    {
      id: "home-18",
      name: "무주 리조트 근처 chalet",
      address: "전북 무주군 ○○로 77",
      hostId: "host-l",
      status: "paused",
      summary: "리조트 인근 스키·힐링 샬레 (시즌 준비)",
      region: "전북",
      locationLabel: "전북 무주",
      pricePerNight: 155000,
      rating: 4.9,
      reviewCount: 15,
      guests: 6,
      bedrooms: 3,
      beds: 4,
      baths: 2,
      propertyType: "샬레",
      amenities: ["스키장 근처", "벽난로", "와이파이", "주차", "주방"],
      photos: [],
      photoTheme: "mountain",
      hostName: "준혁",
      hostBio: "겨울 시즌 오픈을 준비 중입니다.",
      description: "무주 리조트·덕유산 연계 숙소. 현재 예약 불가(준비 중).",
    },
  ];

  var BOOKINGS = [
    {
      id: "b1",
      propertyId: "home-1",
      guestName: "김여행",
      guestId: "guest-demo",
      checkIn: "2026-05-20",
      checkOut: "2026-05-22",
      status: "confirmed",
      note: "늦은 체크인 가능 여부 문의 예정",
    },
    {
      id: "b2",
      propertyId: "home-5",
      guestName: "김여행",
      guestId: "guest-demo",
      checkIn: "2026-06-10",
      checkOut: "2026-06-13",
      status: "pending",
      note: "아기 침대 필요",
    },
    {
      id: "b3",
      propertyId: "home-2",
      guestName: "박체류",
      guestId: "guest-other",
      checkIn: "2026-02-10",
      checkOut: "2026-02-12",
      status: "done",
      note: "",
    },
    {
      id: "b4",
      propertyId: "home-9",
      guestName: "이숙박",
      guestId: "guest-other",
      checkIn: "2026-04-01",
      checkOut: "2026-04-03",
      status: "confirmed",
      note: "",
    },
  ];

  var MESSAGES = [
    {
      id: "m1",
      propertyId: "home-1",
      bookingId: "b1",
      fromRole: "guest",
      fromName: "김여행",
      subject: "체크인 시간 문의",
      body: "20일 저녁 9시쯤 도착 예정인데 가능할까요?",
      status: "open",
      createdAt: "2026-03-18",
    },
    {
      id: "m2",
      propertyId: "home-5",
      bookingId: "b2",
      fromRole: "guest",
      fromName: "김여행",
      subject: "아기 침대 문의",
      body: "6월 예약 건에 아기 침대 추가 가능할까요?",
      status: "open",
      createdAt: "2026-05-10",
    },
    {
      id: "m3",
      propertyId: "home-1",
      fromRole: "host",
      fromName: "집주인 A",
      subject: "Re: 체크인 시간",
      body: "9시 이후 도착 가능합니다. 미리 연락 주세요.",
      status: "replied",
      createdAt: "2026-03-18",
    },
  ];

  var STAY_GUIDE = {
    "home-1": {
      checkIn: "15:00 이후 (사전 협의 시 유연)",
      checkOut: "11:00",
      wifi: "Hangro_Guest / 안내 카드 참고",
      parking: "마당 1대 (추가 차량은 사전 문의)",
      rules: "22시 이후 정숙, 실내 금연, 분리수거 준수",
      contact: "010-0000-0001 (민수)",
    },
    "home-2": {
      checkIn: "14:00 이후",
      checkOut: "11:00",
      wifi: "SmallHouse_Guest",
      parking: "마을 입구 공용 주차장",
      rules: "마을 정숙 시간 22시, 야외 화기 주의",
      contact: "010-0000-0002 (지연)",
    },
    "home-5": {
      checkIn: "16:00",
      checkOut: "10:00",
      wifi: "Jeju_Stone_Wall",
      parking: "돌담 앞 1대",
      rules: "실내 금연, 감귤밭 출입 금지",
      contact: "010-0000-0005 (하준)",
    },
    "home-9": {
      checkIn: "15:00",
      checkOut: "11:00",
      wifi: "Gwangalli_View",
      parking: "건물 지하 (호스트 안내)",
      rules: "22시 이후 정숙, 쓰레기 분리배출",
      contact: "010-0000-0009 (예린)",
    },
  };

  var NOTICES = [
    {
      id: "n1",
      title: "봄 시즌 운영 안내",
      body: "3월부터 체크인 안내 문자가 발송됩니다.",
      date: "2026-03-01",
    },
    {
      id: "n2",
      title: "archive 기록 페이지 업데이트",
      body: "첫 유후공간 프로젝트 전·후 비교를 확인할 수 있습니다.",
      date: "2026-02-20",
    },
  ];

  var DEMO_GUEST_ID = "guest-demo";
  var DEMO_HOST_ID = "host-a";

  global.PORTAL_DATA = {
    properties: PROPERTIES,
    bookings: BOOKINGS,
    messages: MESSAGES,
    stayGuide: STAY_GUIDE,
    notices: NOTICES,
    demoGuestId: DEMO_GUEST_ID,
    demoHostId: DEMO_HOST_ID,
    getProperty: function (id) {
      return PROPERTIES.find(function (p) {
        return p.id === id;
      });
    },
    listBookable: function () {
      return PROPERTIES.filter(function (p) {
        return p.status === "active";
      });
    },
    formatPrice: function (n) {
      return "₩" + Number(n).toLocaleString("ko-KR");
    },
    getBooking: function (id) {
      return BOOKINGS.find(function (b) {
        return b.id === id;
      });
    },
    bookingsForGuest: function (guestId) {
      return BOOKINGS.filter(function (b) {
        return b.guestId === guestId;
      });
    },
    bookingsForHost: function (hostId) {
      var ids = PROPERTIES.filter(function (p) {
        return p.hostId === hostId;
      }).map(function (p) {
        return p.id;
      });
      return BOOKINGS.filter(function (b) {
        return ids.indexOf(b.propertyId) !== -1;
      });
    },
    messagesForPropertyIds: function (propertyIds) {
      return MESSAGES.filter(function (m) {
        return propertyIds.indexOf(m.propertyId) !== -1;
      });
    },
    openMessagesCount: function (propertyIds) {
      return MESSAGES.filter(function (m) {
        return propertyIds.indexOf(m.propertyId) !== -1 && m.status === "open";
      }).length;
    },
  };
})(typeof window !== "undefined" ? window : global);
